site_name: Documentation for the ML4DQM/DC notebooks
nav:
    - Home: 'index.md'
    - omsapi:
        - get_oms_data: 'omsapi/get_oms_data.md'
        - omsapi: 'omsapi/omsapi.md'
        - urls: 'omsapi/urls.md'
    - omsinterface:
        - cert: 'omsinterface/cert.md'
        - connectiontools: 'omsinterface/connectiontools.md'
        - get_oms_data: 'omsinterface/get_oms_data.md'
        - omstools: 'omsinterface/omstools.md'
        - urls: 'omsinterface/urls.md'
    - src:
        - HistStruct: 'src/HistStruct.md'
        - classifiers:
            - AutoEncoder: 'src/classifiers/AutoEncoder.md'
            - HistogramClassifier: 'src/classifiers/HistogramClassifier.md'
            - MaxPullClassifier: 'src/classifiers/MaxPullClassifier.md'
            - NMFClassifier: 'src/classifiers/NMFClassifier.md'
            - TemplateBasedClassifier: 'src/classifiers/TemplateBasedClassifier.md'
        - cloudfitters:
            - CloudFitter: 'src/cloudfitters/CloudFitter.md'
            - ExponentialFitter: 'src/cloudfitters/ExponentialFitter.md'
            - GaussianKdeFitter: 'src/cloudfitters/GaussianKdeFitter.md'
            - LogNormalFitter: 'src/cloudfitters/LogNormalFitter.md'
            - SeminormalFitter: 'src/cloudfitters/SeminormalFitter.md'
    - utils:
        - autoencoder_utils: 'utils/autoencoder_utils.md'
        - clustering_utils: 'utils/clustering_utils.md'
        - csv_utils: 'utils/csv_utils.md'
        - dataframe_utils: 'utils/dataframe_utils.md'
        - generate_data_2d_utils: 'utils/generate_data_2d_utils.md'
        - generate_data_utils: 'utils/generate_data_utils.md'
        - hist_utils: 'utils/hist_utils.md'
        - json_utils: 'utils/json_utils.md'
        - plot_utils: 'utils/plot_utils.md'
        - refruns_utils: 'utils/refruns_utils.md'
